FROM node:12.2.0-alpine

EXPOSE 3000

WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

RUN npm install -g yarn

# install and cache app dependencies
COPY web-client/ /app/
RUN yarn install 

# start app
CMD ["yarn", "start"]
