# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:

env_config: &env
  CI: true
  REACT_APP_API_BASE_URL: https://caolo.herokuapp.com
  REACT_APP_MESSAGES_URL: wss://caolo.herokuapp.com/simulation

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Check backend
        run: curl ${REACT_APP_API_BASE_URL}
        env: *env
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - name: e2e tests
        env: *env
        run: |
          yarn start & npx wait-on "http://localhost:3000"
          npx cypress run
